# Generated by Django 6.0.3 on 2026-05-19 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screen', '0002_hplc_asp'),
    ]

    operations = [
        migrations.AddField(
            model_name='hplc',
            name='ace_high',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='hplc',
            name='ace_low',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='hplc',
            name='asp_high',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='hplc',
            name='asp_low',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='hplc',
            name='benz_high',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='hplc',
            name='benz_low',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='hplc',
            name='caf_high',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='hplc',
            name='caf_low',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='hplc',
            name='sorb_high',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='hplc',
            name='sorb_low',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
